title: Matt Cerda Projects
description: Explore my diverse portfolio of cyber projects, showcasing solutions in cybersecurity, threat analysis, and ethical hacking. 
Each project demonstrates my commitment to enhancing security and my ability to handle complex challenges in the tech landscape.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
